In [86]:
import numpy as np
import json

In [87]:



def pad_ARC(arr, pad_value=10, final_size=(12, 12)):
    # Get the current size of the array
    current_size = arr.shape
    
    # Initialize the padding list
    padding = []
    
    # Calculate the amount of padding needed for each dimension
    for i in range(len(final_size)):
        pad_amount = max(0, final_size[i] - current_size[i])
        padding.append((0, pad_amount))
    
    # Pad the array
    padded_arr = np.pad(arr, padding, mode='constant', constant_values=pad_value)
    
    return padded_arr

In [88]:
test_file = open("E:/aolabs/arc-prize/ARC-AGI/data/training/445eab21.json")

test_data = json.load(test_file)


In [89]:
vector1 = np.array(test_data['train'][0]['input'])

In [90]:
vector1

array([[0, 7, 7, 7, 7, 0, 0, 0, 0, 0],
       [0, 7, 0, 0, 7, 0, 0, 0, 0, 0],
       [0, 7, 0, 0, 7, 0, 0, 0, 0, 0],
       [0, 7, 7, 7, 7, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 8, 8, 8, 8, 8, 0, 0],
       [0, 0, 0, 8, 0, 0, 0, 8, 0, 0],
       [0, 0, 0, 8, 0, 0, 0, 8, 0, 0],
       [0, 0, 0, 8, 8, 8, 8, 8, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [91]:
pad_ARC(vector1)

array([[ 0,  7,  7,  7,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  7,  0,  0,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  7,  0,  0,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  7,  7,  7,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  8,  8,  8,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  0,  0,  0,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  0,  0,  0,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  8,  8,  8,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [92]:
color_to_binary = [
    '0000', # black
    format(1, '04b'), # blue
    format(2, '04b'), # red
    format(3, '04b'), # green
    format(4, '04b'), # yellow
    format(5, '04b'), # grey
    format(6, '04b'), # pink
    format(7, '04b'), # orange
    format(8, '04b'), # l blue
    format(9, '04b'), # maroon
    '1010', # void / null   #asigning it 1010, because its 10(decimal) in binary.
]

In [94]:
color_to_binary[10]

'1010'

In [95]:
def ARC_to_binary( input_padded):

    input_flat = input_padded.flatten()
    inn_stringvec = ""
    for p in input_flat:
        inn_stringvec += color_to_binary[p]  #this line adds 4 bits 
    
    inn_narray = np.asarray(list(inn_stringvec), dtype=int)

    return inn_narray

In [108]:
pad_vec1 = pad_ARC(vector1)
bin_pad_vec1 = ARC_to_binary(pad_vec1)
print(ARC_to_binary(pad_vec1), len(ARC_to_binary(pad_vec1)))

#in the printed array, first four represent the 1st block, next four represenst the next block..and so on.

[0 0 0 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0
 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0
 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0
 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 

In [97]:
pad_vec1

array([[ 0,  7,  7,  7,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  7,  0,  0,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  7,  0,  0,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  7,  7,  7,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  8,  8,  8,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  0,  0,  0,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  0,  0,  0,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  8,  8,  8,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [123]:
#function to convert binary color to integer color
def binary_to_color(binary_color):
    decimal = 0
    for digit in binary_color:
        decimal = decimal*2 + int(digit)
    return decimal   

def binary_to_ARC(binary_input, original_shape):
    # Initialize an empty list to hold the chunks of 4 bits
    chunks = []
    
    # Split the binary input into chunks of 4 bits
    for i in range(0, len(binary_input), 4):
        chunk = ''.join(map(str, binary_input[i:i+4]))
        chunks.append(chunk)
    
    # Initialize an empty list to hold the color indices
    color_indices = []
    
    # Convert binary chunks back to their original color indices
    for chunk in chunks:
        color_index = binary_to_color(chunk)
        color_indices.append(color_index)
    
    # Convert the list of color indices to a numpy array and reshape it to the original shape
    output_array = np.array(color_indices).reshape(original_shape)
    
    return output_array

In [124]:
binary_to_ARC(bin_pad_vec1, (12,12))

array([[ 0,  7,  7,  7,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  7,  0,  0,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  7,  0,  0,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  7,  7,  7,  7,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  8,  8,  8,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  0,  0,  0,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  0,  0,  0,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  8,  8,  8,  8,  8,  0,  0, 10, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])